version: '3.3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PROJECT_ROOT}:/var/www/html

  php:
    build: ./php/
    image: jakubskrz/php-dev
    expose:
      - 9000
    links:
      - mailcatcher
      - memcached
      - postgres
      - mssql
    volumes:
      - ./config/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ${PROJECT_ROOT}:/var/www/html
    env_file:
      - .env

  mailcatcher:
    image: tophfr/mailcatcher
    expose:
      - "25"
    ports:
      - "1080:80"

  memcached:
    image: memcached

  postgres:
    image: postgres:9.6
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  mssql:
    image: microsoft/mssql-server-linux
    volumes:
      - mssqldata:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}

  composer:
    image: composer
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.composer:/composer
      - ${PROJECT_ROOT}:/var/www/html
    working_dir: /var/www/html

volumes:
  dbdata:
  mssqldata:
