version: '2'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - app
      - nginxconf

  php:
    build: ./php/
    expose:
      - 9000
    links:
      - mailcatcher
      - postgres
    volumes:
      - ./config/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    volumes_from:
      - app

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "1025:25"
      - "1080:80"

  postgres:
    image: postgres:9.6
    volumes_from:
      - dbdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecretPass4DB

  app:
    image: php:7.1-fpm
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
    command: "true"

  dbdata:
    image: postgres:9.6
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: "true"

  nginxconf:
    image: nginx:1.13
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    command: "true"

volumes:
  app:
  dbdata:
  nginxconf:
